### ISSUE TITLE
TODO list for details

### ISSUE THREAD

**Issue by matthewbentley** [beta-nu-theta-chi/ox-dashboard#12]
TODO:
- [x] VP form for who's in the house
- [x] Detail manager form for who does house
- [x] Model for storing a detail (completed or pending)
- [x] Some way to keep track of Sunday detail groups
  - [x] Some way to store groups
  - [x] Some way to create/modify groups
- [x] Load details from yaml file on startup
- [x] Button to assign and email Thursday details - TODO: actually send the emails
- [x] Button to assign and email Sunday details - TODO: actually send the emails
- [x] Complete Thursday detail button
- [x] Complete Sunday detail button
- [x] Page(s) for users to see current and past details
- [ ] Detail manager page to track completions and fines

Still TODO: a better way to create / manage / delete Sunday detail groups.

Maybe:
- [ ] Random spot check button for detail manager
- [ ] Also track kitchen details?
- [ ] Detail manager form for who does kitchen details

**Comment by matthewbentley** [comment]
Closing this, as the majority of these features are implemented and working.
